import { Document, IndexDescription } from "mongodb";

export const GROUPS_COLLECTION = "groups" as const;

export type GroupStatus = "WAITING" | "READY" | "PLAYING" | "FINISHED";

export interface GroupDoc extends Document {
    _id: Document["_id"];
    groupId: string;
    name: string;
    passwordHash: string;
    status: "WAITING" | "READY" | "PLAYING" | "FINISHED";
    activeSessionId: Document["_id"] | null;
    /**
     * Lobby selection token. Generated by POST /groups/select.
     * Identifies the browser that currently "owns" the group in the lobby.
     * Cleared on release or when the game starts.
     * NOT a user credential — only session ownership for the selected group.
     */
    selectionToken: string | null;
    selectionExpiresAt: Date | null;
    createdAt: Date;
    updatedAt: Date;
}

export const groupsValidator = {
    $jsonSchema: {
        bsonType: "object",
        required: [
            "groupId",
            "name",
            "passwordHash",
            "status",
            "selectionToken",
            "selectionExpiresAt",
            "createdAt",
            "updatedAt",
        ],
        properties: {
            _id: { bsonType: "objectId" },
            groupId: {
                bsonType: "string",
                pattern: "^Group(0[1-9]|10)$",
                description: "Business id, must match Group01..Group10",
            },
            name: {
                bsonType: "string",
                minLength: 1,
                description: "Display name of the group",
            },
            passwordHash: {
                bsonType: "string",
                pattern: "^\\$2[aby]\\$",
                description: "Bcrypt hash marker; refuses plain text",
            },
            status: {
                enum: ["WAITING", "READY", "PLAYING", "FINISHED"],
                description:
                    "Lobby/Game lifecycle state of the group. WAITING = selectable. " +
                    "READY = a browser has claimed it but the game has not started. " +
                    "PLAYING = a GameSession is in progress (IN_PROGRESS). " +
                    "FINISHED = the GameSession ended (submitted or expired).",
            },
            activeSessionId: {
                bsonType: ["objectId", "null"],
                description: "Reference to the currently open session, if any",
            },
            selectionToken: {
                bsonType: ["string", "null"],
                pattern: "^st_[A-Za-z0-9_-]{8,}$",
                description:
                    "Lobby session ownership token. Null when no browser has claimed the group.",
            },
            selectionExpiresAt: {
                bsonType: ["date", "null"],
                description:
                    "Expiry of selectionToken. Null when the group is not claimed.",
            },
            createdAt: { bsonType: "date" },
            updatedAt: { bsonType: "date" },
        },
        additionalProperties: false,
    },
};

export const groupsIndexes: IndexDescription[] = [
    { key: { groupId: 1 }, name: "groupId_unique", unique: true },
    { key: { status: 1 }, name: "status_idx" },
];